services:
  # 1. Base de Datos Centralizada
  db-central:
    image: postgres:15-alpine
    container_name: shservices-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shservices-net

  # 2. Broker de Mensajes (Coreografía)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: shservices-broker
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shservices-net

  # 3. Microservicio de Autenticación e Identidad (IAM)
  auth-service:
    build: ./auth-service
    container_name: shservices-auth
    restart: always
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-central:5432/${POSTGRES_DB}"
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ADMIN1_USER: ${ADMIN1_USER}
      ADMIN1_PASS: ${ADMIN1_PASS}
      ADMIN2_USER: ${ADMIN2_USER}
      ADMIN2_PASS: ${ADMIN2_PASS}
      ADMIN3_USER: ${ADMIN3_USER}
      ADMIN3_PASS: ${ADMIN3_PASS}
    depends_on:
      - db-central
    networks:
      - shservices-net

  # 4. Microservicio de Tickets
  ticket-service:
    build: ./ticket-service
    container_name: shservices-tickets
    restart: always
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-central:5432/${POSTGRES_DB}"
      RABBITMQ_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/"
    depends_on:
      - db-central
      - rabbitmq
    networks:
      - shservices-net

  # 5. Microservicio de Almacén e Inventario
  almacen-service:
    build: ./almacen-service
    container_name: shservices-almacen
    restart: always
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-central:5432/${POSTGRES_DB}"
      RABBITMQ_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/"
    depends_on:
      - db-central
      - rabbitmq
    networks:
      - shservices-net

  almacen-worker:
    build: ./almacen-service
    command: python consumidor.py
    restart: always
    depends_on:
      - db-central
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin_corporativo:shservices_master_secure_db_2026@db/shservices_enterprise
    networks:
      - shservices-net

  # 6. Escudo Perimetral (API Gateway)
  api-gateway:
    build: ./api-gateway
    container_name: shservices-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - ticket-service
      - almacen-service
      - auth-service
    networks:
      - shservices-net

  # 7. Panel Web (Frontend React + Vite)
  panel-web:
    build: ./panel-web
    container_name: shservices-panel
    ports:
      - "5173:5173"
    volumes:
      - ./panel-web:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - shservices-net

networks:
  shservices-net:
    driver: bridge

volumes:
  pgdata: